class Variables:
    outcomes = ['group_0_crimes_50m',
                'group_1_crimes_50m',
                'group_2_crimes_50m',
                'group_3_crimes_50m',
                'group_4_crimes_50m',
                'group_0_crimes_100m',
                'group_1_crimes_100m',
                'group_2_crimes_100m', 
                'group_3_crimes_100m',
                'group_4_crimes_100m',
                'group_0_crimes_500m',
                'group_1_crimes_500m',
                'group_2_crimes_500m', 
                'group_3_crimes_500m',
                'group_4_crimes_500m',
                'group_0_crimes_1000m',
                'group_1_crimes_1000m',
                'group_2_crimes_1000m', 
                'group_3_crimes_1000m',
                'group_4_crimes_1000m']

